### ISSUE TITLE
Error: Cannot find module 'write'

### ISSUE THREAD

**Issue by bradsiefert** [hirnidrin/gridsome-plugin-query2file#1]
Hello, I really appreciate you making this package, it's perfect for a project I'm working on now! I'm having a problem though getting it to work. I've tried it on my site, a generic starter, and on NPM Runkit and I've gotten the same error:

_Error: Cannot find module 'write'_

**Link to error on NPM Runkit:**
https://npm.runkit.com/gridsome-plugin-query2file

Maybe it's on my end, but I wanted to raise it as an issue. Thanks in advance.

**Comment by hirnidrin** [comment]
Thanks for pointing this out. I added the missing dependency and tested in context of the minimal 'gridsome-sarter-default' site.

**Comment by bradsiefert** [comment]
I'm so glad it was easy! I'm also glad I wasn't crazy because I couldn't get it to work 😜. I'm excited to use it because I've been trying to implement vue-fuse on my site for searching and I wanted an automated way to generate a JSON file.
